# fly.toml file generated for winter-surf-8470 on 2022-12-09T13:39:46-03:00

app = "winter-surf-8470"

[[services]]

  [[services.ports]]
    handlers = ["http"]
    internal_port = 8080
    port = 80
    protocol = "tcp"

  [[services.ports]]
    handlers = ["tls", "http"]
    internal_port = 8080
    port = 443
    protocol = "tcp"
